# Generated by Django 4.0.3 on 2022-05-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_dat',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
